MDM_TestMissions = {}

function MDM_TestMissions.MDM_SalieriMissions()
  print("---------------Salieri Missions M1_BackyardTrouble")
  MDM_SalieriMissions.M1_BackyardTrouble()
  print("---------------Salieri Missions M2_WhiskyWhopper")
  MDM_SalieriMissions.M2_WhiskyWhopper()
  print("---------------Salieri Missions M3_GangWar1")
  MDM_SalieriMissions.M3_GangWar1()
  print("---------------Salieri Missions M4_GangWar2")
  MDM_SalieriMissions.M4_GangWar2()
  print("---------------Salieri Missions M5_Escalation")
  MDM_SalieriMissions.M5_Escalation()
end

function MDM_TestMissions.MDM_LucasBertone()
  print("---------------Lucas Bertone M1_1_Fairplay")
  MDM_LucasBertone.M1_1_Fairplay()
  print("---------------Lucas Bertone M2_1_TripToTheCountry")
  MDM_LucasBertone.M2_1_TripToTheCountry()
  print("---------------Lucas Bertone M2_2_TripToTheCountry")
  MDM_LucasBertone.M2_2_TripToTheCountry()
  print("---------------Lucas Bertone M3_1_Omerta")
  MDM_LucasBertone.M3_1_Omerta()
  print("---------------Lucas Bertone M3_2_Omerta")
  MDM_LucasBertone.M3_2_Omerta()
  print("---------------Lucas Bertone M4_1_LuckyBastard")
  MDM_LucasBertone.M4_1_LuckyBastard()
  print("---------------Lucas Bertone M4_2_LuckyBastard")
  MDM_LucasBertone.M4_2_LuckyBastard()
  print("---------------Lucas Bertone M5_1_CremeDeLaCreme")
  MDM_LucasBertone.M5_1_CremeDeLaCreme()
  print("---------------Lucas Bertone M5_2_CremeDeLaCreme")
  MDM_LucasBertone.M5_2_CremeDeLaCreme()
  print("---------------Lucas Bertone M6_1_Election")
  MDM_LucasBertone.M6_1_Election()
  print("---------------Lucas Bertone M6_2_Election")
  MDM_LucasBertone.M6_2_Election()
  print("---------------Lucas Bertone M7_1_Robbery")
  MDM_LucasBertone.M7_1_Robbery()
  print("---------------Lucas Bertone M7_2_Robbery")
  MDM_LucasBertone.M7_2_Robbery()
end

function MDM_TestMissions.TestMissions()
  print("---------------Testmissions GetInCar")
  TestMissions.GetInCar()
  print("---------------Testmissions KillMission")
  TestMissions.KillMission()
  print("---------------Testmissions WaypointMission")
  TestMissions.WaypointMission()
  print("---------------Testmissions GangWarTest")
  TestMissions.GangWarTest()
  print("---------------Testmissions DestroyCarInAreaTest")
  TestMissions.DestroyCarInAreaTest()
  print("---------------Testmissions HosileZoneTest")
  TestMissions.HostileZoneTest()
  print("---------------Testmissions DuelTest")
  TestMissions.DuelTest()
  print("---------------Civil Wander Test")
  TestMissions.CivilWanderTest()
  print("---------------Pursuit Test")
  TestMissions.PursuitTest()
  print("---------------Carchase Test")
  TestMissions.CarchaseTest()

  MDM_AssassinationMission.UnitTest()
end
