MDM_TestMissions = {}

function MDM_TestMissions.MDM_SalieriMissions()
  print("---------------Salieri Missions M1_BackyardTrouble")
  MDM_SalieriMissions.M1_BackyardTrouble()
  print("---------------Salieri Missions M2_WhiskyWhopper")
  MDM_SalieriMissions.M2_WhiskyWhopper()
  print("---------------Salieri Missions M3_GangWar1")
  MDM_SalieriMissions.M3_GangWar1()
  print("---------------Salieri Missions M4_GangWar2")
  MDM_SalieriMissions.M4_GangWar2()
  print("---------------Salieri Missions M5_Escalation")
  MDM_SalieriMissions.M5_The_Camino_Escalation()
end

function MDM_TestMissions.TestMissions()
  print("---------------Testmissions GetInCar")
  TestMissions.GetInCar()
  print("---------------Testmissions KillMission")
  TestMissions.KillMission()
  print("---------------Testmissions WaypointMission")
  TestMissions.WaypointMission()
  print("---------------Testmissions GangWarTest")
  TestMissions.GangWarTest()
  print("---------------Testmissions DestroyCarInAreaTest")
  TestMissions.DestroyCarInAreaTest()
  print("---------------Testmissions HosileZoneTest")
  TestMissions.HostileZoneTest()
  print("---------------Testmissions DuelTest")
  TestMissions.DuelTest()
  print("---------------Civil Wander Test")
  TestMissions.CivilWanderTest()
  print("---------------Pursuit Test")
  TestMissions.PursuitTest()
  print("---------------Carchase Test")
  TestMissions.CarchaseTest()

  MDM_AssassinationMission.UnitTest()
end
